In [1]:
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
from collections import Counter
import numpy as np

In [2]:
data = pd.read_csv('6ktweets.csv', index_col=0)
data

,Date,tweets,User Location,hashtag
0,10/14/2019 0:47,Why do they keep electing elites that have mil...,United States,#MAGA2020
1,10/14/2019 0:46,No Shame! \nThanks @carlosrossimc for the vers...,United States,#MAGA2020
2,10/14/2019 0:46,@vocabulori @walterowensgrpa @IlhanMN Aw anoth...,NaN,#MAGA2020
3,10/14/2019 0:45,@realDonaldTrump @FoxNews needs to dump Wallac...,"Boston, MA",#MAGA2020
4,10/14/2019 0:45,President Trump is 100% Correct on Syria Withd...,Florida of course!,#MAGA2020
...,...,...,...,...
5995,10/11/2019 0:18,Trumpâ€™s children take in millions overseas as ...,"Portland, OR",#MAGA2020
5996,10/11/2019 0:18,@THeinrich22 @richard91814483 Amazing!!!! #MA...,NaN,#MAGA2020
5997,10/11/2019 0:17,ðŸš¨BREAKINGðŸš¨\n#Whistleblower Worked With #JoeBid...,USA,#MAGA2020
5998,10/11/2019 0:17,"Gosh, imagine that- a spineless business failu...","Freehold, NJ",#MAGA2020
5999,10/11/2019 0:17,@MADE__USA @DonaldJTrumpJr @realDonaldTrump #M...,NaN,#MAGA2020

In [3]:
threestates = []
for x in data['User Location'].unique():
    if 'michigan' in str(x).lower() or 'pennsylvania'in str(x).lower() or 'wisconsin' in str(x).lower() or str(x).lower().endswith(', mi') or str(x).lower().endswith('pa') or str(x).lower().endswith('wi'):
        threestates.append(x)

threestates

['Michigan, USA',
 'Pennsylvania',
 'Pennsylvania, USA',
 'Verona WI',
 'Altoona PA',
 'Wisconsin, USA',
 'Lehigh Valley PA',
 'DELCO Phila, Pa',
 'Philadelphia, PA',
 'Eastern PA',
 'Warren, PA',
 'Butler, PA',
 'Somewhere in Pennsylvania!',
 'Little Chute, WI',
 'Easton, PA',
 'Holt, MI',
 'Grand Blanc, MI',
 'Pittsburgh, PA',
 'Tempe, AZ & Door County, WI',
 'Waterford, PA',
 'Lebanon, PA',
 'Monaca, PA',
 'Wisconsin, USA ',
 'Loganville, PA',
 'Michigan U.S.A.',
 'Near Pittsburgh PA',
 'Western Pa',
 'Detroit, MI',
 'Huntingdon Valley, PA',
 'Oakland County, Mi',
 'Cranberry Township, PA',
 'Hobart, WI',
 'Lancaster, PA',
 'Clinton, MI',
 'Southfield, MI',
 'Michigan',
 'Lock Haven, PA',
 'Ligonier, PA',
 'Davidsville, PA',
 'New York / Pennsylvania',
 'Mt. Pleasant Michigan',
 'Superior, WI',
 'Port Huron, MI',
 'PA']

In [4]:
for index, row in data.iterrows():
    if row['User Location'] in threestates:
        row['User Location'] = 'battleground'

In [7]:
# data1 = data.copy()
data1[data1['User Location'] == 'battleground']

,Date,tweets,User Location,hashtag
13,10/14/2019 0:35,battleground@NBCNews Unfounded? You people ar...,battleground,#MAGA2020
32,10/14/2019 0:24,battleground@BillKristol Drunk again? #MAGA2020,battleground,#MAGA2020
54,10/14/2019 0:04,battleground@DavidJHarrisJr @realDonaldTrump T...,battleground,#MAGA2020
164,10/13/2019 22:38,battleground@thehill @realDonaldTrump You donâ€™...,battleground,#MAGA2020
203,10/13/2019 22:15,battleground#tcot #ccot #LNYHBT #maga2020 #yco...,battleground,#MAGA2020
...,...,...,...,...
5888,10/11/2019 0:47,"battlegroundI agree, @charliekirk11 !#MAGA2020...",battleground,#MAGA2020
5900,10/11/2019 0:46,battlegroundMinneapolis police officer running...,battleground,#MAGA2020
5905,10/11/2019 0:44,battlegroundDavid Bossie: Impeachment inquiry?...,battleground,#MAGA2020
5908,10/11/2019 0:44,battleground@SpeakerPelosi @RepAdamSchiff Fact...,battleground,#MAGA2020
5933,10/11/2019 0:39,battlegroundTime to support the beautiful wome...,battleground,#MAGA2020

In [6]:
data1 = data.copy()
data1.loc[data1['User Location'] == 'battleground','tweets'] = 'battleground' + data1['tweets']
data1

,Date,tweets,User Location,hashtag
0,10/14/2019 0:47,Why do they keep electing elites that have mil...,United States,#MAGA2020
1,10/14/2019 0:46,No Shame! \nThanks @carlosrossimc for the vers...,United States,#MAGA2020
2,10/14/2019 0:46,@vocabulori @walterowensgrpa @IlhanMN Aw anoth...,NaN,#MAGA2020
3,10/14/2019 0:45,@realDonaldTrump @FoxNews needs to dump Wallac...,"Boston, MA",#MAGA2020
4,10/14/2019 0:45,President Trump is 100% Correct on Syria Withd...,Florida of course!,#MAGA2020
...,...,...,...,...
5995,10/11/2019 0:18,Trumpâ€™s children take in millions overseas as ...,"Portland, OR",#MAGA2020
5996,10/11/2019 0:18,@THeinrich22 @richard91814483 Amazing!!!! #MA...,NaN,#MAGA2020
5997,10/11/2019 0:17,ðŸš¨BREAKINGðŸš¨\n#Whistleblower Worked With #JoeBid...,USA,#MAGA2020
5998,10/11/2019 0:17,"Gosh, imagine that- a spineless business failu...","Freehold, NJ",#MAGA2020
5999,10/11/2019 0:17,@MADE__USA @DonaldJTrumpJr @realDonaldTrump #M...,NaN,#MAGA2020

In [6]:
people_trump = ['Trump','battleground']
trump_df = pd.DataFrame(columns = people_trump)

def candidates_mentioned(item):
    if p in item:
        return 1
    else:
        return 0
      
for p in people_trump:
    trump_df[p] = data1['tweets'].apply(candidates_mentioned)
    
    
    
people_dem = ['Biden','battleground']
dem_df = pd.DataFrame(columns = people_dem)

def candidates_mentioned(item):
    if p in item:
        return 1
    else:
        return 0
      
for p in people_dem:
    dem_df[p] = data1['tweets'].apply(candidates_mentioned)

In [7]:
trump_df

      Trump  battleground
0         1             0
1         0             0
2         0             0
3         1             0
4         1             0
...     ...           ...
5995      1             0
5996      0             0
5997      1             0
5998      0             0
5999      1             0

[6000 rows x 2 columns]

In [8]:
df1=pd.DataFrame(columns = people_trump)
for i in range(len(people_trump)):
    new_list = []
    for j in range(len(people_trump)):
        if (i!=j):
            numerator = ((trump_df[people_trump[i]] + trump_df[people_trump[j]]) > 1).sum()
            denominator = trump_df[people_trump[j]].sum()*trump_df[people_trump[i]].sum()
            lift = numerator*len(trump_df)/denominator
            df1.loc[people_trump[i],people_trump[j]] = lift
print ('Below are the lift ratios among Trump and battleground')
df1

Below are the lift ratios among Trump and battleground

                 Trump battleground
Trump              NaN     0.990447
battleground  0.990447          NaN

In [9]:
df2=pd.DataFrame(columns = people_dem)
for i in range(len(people_dem)):
    new_list = []
    for j in range(len(people_dem)):
        if (i!=j):
            numerator = ((dem_df[people_dem[i]] + dem_df[people_dem[j]]) > 1).sum()
            denominator = dem_df[people_dem[j]].sum()*dem_df[people_dem[i]].sum()
            lift = numerator*len(dem_df)/denominator
            df2.loc[people_dem[i],people_dem[j]] = lift
print ('Below are the lift ratios among Biden and battleground')
df2

Below are the lift ratios among Biden and battleground

                Biden battleground
Biden             NaN      1.92235
battleground  1.92235          NaN

## Lift analysis

In [10]:
liftdf = pd.DataFrame(index=['Battleground'],columns=['Trump','Biden'])
liftdf.iloc[0,0]=df1.iloc[0,1]
liftdf.iloc[0,1]=df2.iloc[0,1]
liftdf

                 Trump    Biden
Battleground  0.990447  1.92235

In [11]:
data2 = data1[data1['User Location'] == 'battleground']

In [12]:
trumpsenti=[]
analyzer = SentimentIntensityAnalyzer()
for index, row in data2.iterrows():
    if 'trump' in row['tweets'].lower():
        vs = analyzer.polarity_scores(row['tweets'])
        trumpsenti.append(vs['compound'])

In [13]:
demsenti=[]
analyzer = SentimentIntensityAnalyzer()
for index, row in data2.iterrows():
    if 'biden' in row['tweets'].lower():
        vs = analyzer.polarity_scores(row['tweets'])
        demsenti.append((vs['compound']))

## Sentiment analysis

In [14]:
sentimentdf = pd.DataFrame(index=['Battleground'],columns=['Trump','Biden'])
sentimentdf.iloc[0,0]=np.mean(trumpsenti)
sentimentdf.iloc[0,1]=np.mean(demsenti)
sentimentdf

                 Trump      Biden
Battleground  0.136974  0.0489545